import { ProfileBackupApplicationService } from "@learn-language/application/workspace";
import { normalizeCourseLearningRecord, type CourseLearningRecord } from "@learn-language/application/learning-record";
import * as DocumentPicker from "expo-document-picker";
import { File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import type { SQLiteLearningProfileRepository } from "./storage";
interface MobileBackup { schemaVersion: 1; kind: "learn-language-mobile-backup"; exportedAt: string; records: CourseLearningRecord[]; }
export async function exportMobileBackup(records: readonly CourseLearningRecord[]) { const stamp = new Date().toISOString().replaceAll(":", "-"); const file = new File(Paths.cache, `learnlanguage-mobile-${stamp}.json`); if (file.exists) file.delete(); file.create(); const backup: MobileBackup = { schemaVersion: 1, kind: "learn-language-mobile-backup", exportedAt: new Date().toISOString(), records: [...records] }; file.write(JSON.stringify(backup, null, 2)); if (!(await Sharing.isAvailableAsync())) throw new Error("当前设备不支持系统分享"); await Sharing.shareAsync(file.uri, { mimeType: "application/json", dialogTitle: "导出 LearnLanguage 学习备份" }); }
export async function importMobileBackup(repository: SQLiteLearningProfileRepository) { const picked = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (picked.canceled) return undefined; const asset = picked.assets[0]; if (!asset) throw new Error("没有读取到备份文件"); const raw = await new File(asset.uri).text(); const input = JSON.parse(raw) as Partial<MobileBackup>; if (input.schemaVersion !== 1 || input.kind !== "learn-language-mobile-backup" || !Array.isArray(input.records)) throw new Error("不是受支持的 LearnLanguage 移动端备份"); const records = input.records.map(normalizeCourseLearningRecord); if (records.some((record) => !record)) throw new Error("备份包含损坏的学习记录"); return new ProfileBackupApplicationService(repository).restore(records as CourseLearningRecord[]); }
